schema: "lib/schema/**/*.graphqls"
schemaEntrypoint: "lib/type-defs.graphqls"
documents: "**/*.graphql"
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
cacheDir: __generated__
config:
  maybeValue: T
