version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3030:3030"
      - "4040:4040"
    environment: 
      MYSQL_USER: develop
      MYSQL_PASSWORD: "123456"
      MYSQL_HOST: mysql
      MYSQL_DB: reactcms
      MYSQL_PORT: "3306"
      NODE_ENV: dev
    volumes:
      - .:/app
    command: ./wait-for-it.sh mysql:3306 -- npm run dev
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    restart: always
    ports: 
      - "3306"
    volumes:
      - ./dbdata:/var/lib/mysql
    environment: 
      MYSQL_USER: develop
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: reactcms
      MYSQL_ROOT_PASSWORD: "123456"
