name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.extract_branch.outputs.branch }}
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: "12.9.1"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache
        uses: actions/cache@v1.1.0
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-cache-
      - run: yarn install
      - name: Create environment file .env
        shell: bash
        run: cp sample.env .env
      - name: Create database
        run: yarn seed
      - run: yarn build
      - run: ./utils/createArtifacts.sh
      - name: Post to google cloud
        run: |
          curl -X POST -L \
            -F "metadata={name : 'vendor-zip.zip'};type=application/json;charset=UTF-8" \
            -F "artifact=@vendor-zip.zip;type=application/zip" \
            -F 'data={"key":"${{ secrets.DEPLOY_TOKEN }}", "domain":"ajaxtown.com"}' \
            "http://ajaxtown.com/deploy"
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./vendor-zip/vendor.zip ./vendor-zip
      - uses: actions/upload-artifact@master
        with:
          name: vendor
          path: ./vendor-zip/vendor.zip
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
