name: Deployment Workflow
on:
  push:
    branches:
      - "*"

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run build
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: 130.211.80.253
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "."
          target: /var/www/html/letterpad-next
          debug: true
