name: Deployment Workflow
on:
  push:
    branches:
      - "*"

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh key
        uses: nogsantos/scp-deploy@master
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          src: .
          remote: ~/var/www/html/letterpad-next
